//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTutorProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply
    {
        public int apply_id { get; set; }
        public Nullable<int> std_id { get; set; }
        public Nullable<int> tid { get; set; }
        public string slot { get; set; }
        public Nullable<int> aproval_status { get; set; }
        public string tutor_address { get; set; }
    
        public virtual dr dr { get; set; }
        public virtual tutor tutor { get; set; }
    }
}
